# Generated by Django 5.1 on 2024-09-03 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
