# Generated by Django 5.1 on 2024-09-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trees_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trees',
            old_name='created_date',
            new_name='creat_date',
        ),
    ]
