# Generated by Django 5.1 on 2024-09-03 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_created_date_trees_creat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='creat_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
