# Generated by Django 5.1.1 on 2024-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_picture',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
    ]
