# Generated by Django 5.1 on 2024-09-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_community_community_picture'),
        ('api', '0010_rename_user_post_author_post_likes_delete_likes'),
    ]

    operations = [
    ]
