# Generated by Django 5.1 on 2024-09-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20240918_1050'),
        ('api', '0011_merge_20240919_0020'),
    ]

    operations = [
    ]
